### ISSUE TITLE
Documentation generation for all quattor repos

### ISSUE THREAD

**Issue by stdweird** [quattor/release#110]
In particular:
- maven-tools/buildscripts for the test suite documentation
- ncm-ncd for the Component class documentation

**Comment by wdpypere** [comment]
@stdweird OK, I added the config for the documentation to ncm-ncd. (https://github.com/quattor/ncm-ncd/pull/127) . It is building on readthedocs and a preview should be available soon on https://docs-test-comps.readthedocs.io/en/latest/
So when we move the documentation to the new rst format, ncm-ncd will be included.

**Comment by stdweird** [comment]
@wdpypere thx!
