### ISSUE TITLE
Vim Pan syntax highlight 

### ISSUE THREAD

**Issue by samary** [quattor/release#112]
Where can I find the vim syntax highlight plugin for pan ?

**Comment by jouvin** [comment]
Adding @Pansanel (the author) to the discussion.

**Comment by jrha** [comment]
Can be found at https://trac.lal.in2p3.fr/Quattor/wiki/Web/ViEditor

Should be migrated to this repository or (preferably) upstreamed to VIM.

**Comment by Pansanel** [comment]
I should also update this plugin, as it does not contain of new PAN language elements.

**Comment by jrha** [comment]
This should probably go into the pan repository.

**Comment by jrha** [comment]
Closed by quattor/pan#98
