### ISSUE TITLE
build_all_repos: broken by maven 3.3.3

### ISSUE THREAD

**Issue by jrha** [quattor/release#119]
A few days ago maven 3.3.3 dropped into [the repository used by build_all_repos](https://repos.fedorapeople.org/repos/dchen/apache-maven/epel-6/x86_64/), unfortunately there seems to be some problem with the dependencies, because this version fails with

> Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/cli/MavenCli : Unsupported major.minor version 51.0

**Comment by stdweird** [comment]
http://stackoverflow.com/questions/31394456/java-6-unsupported-major-minor-version-51-0
as of mvn 3.3, jdk7 is required. 3.2.5 is latest supported with jdk6.

**Comment by jrha** [comment]
But the package pulls in jdk6...

**Comment by stdweird** [comment]
i made a comment on the packagers blog.

**Comment by stdweird** [comment]
@jrha the rpms in the repo are updated now
https://dingyichen.wordpress.com/2015/10/08/dchens-apache-maven-is-updated-to-3-3-3-for-el7-and-el6/#comment-603

**Comment by jrha** [comment]
Sweet, I'll give it a go if our cloud starts working again.

**Comment by jrha** [comment]
Hmpf, fails on both SL6 and SL7

**Comment by stdweird** [comment]
https://dingyichen.wordpress.com/2015/10/08/dchens-apache-maven-is-updated-to-3-3-3-for-el7-and-el6/#comment-610

https://github.com/quattor/release/pull/120 is a temporary workaround

**Comment by jrha** [comment]
@stdweird the workaround  an be removed now, the `apache-maven-3.3.9-1.el6.noarch` package has fixed this poblem (and we will need maven 3.3.3+ to update our maven plugins soon).

**Comment by jouvin** [comment]
FYI, I started to work on the maven plugin upgrade a couple of weeks ago but had a problem with one of them that needs our configuration to be adjusted... Unfortunately I failed to identify what should be done... A first step would be to upgrade everything possible: we are relying on old versions for some of them and that may just increase our problems...
