### ISSUE TITLE
Cron component bug

### ISSUE THREAD

**Issue by jrha** [quattor/release#122]
I was trying to use the cron component in the profile of our machine. I would like just to report a tiny bug I found. If I configure my CDB profile like this:

```
"/software/components/cron/entries" = push(
  nlist( "name", "check disk",
  "user", "root",
  "group", "root",
  "frequency", "23 12 * * *",
  "command", "..."));
```

i.e. with a space in the name, then, the implemented cronjob will not be valid:

[...]
... &gt;&gt; /var/log/check disk.ncm-cron.log 2&gt;&1
[...]

as you can see the space is not well escaped. And hence the log file would not be correctly created.

Reported by: *anonymous

**Comment by ned21** [comment]
No longer able to reproduce in 17.7:

```
$ rifle -c /software/components/cron | grep check
/software/components/cron/entries/3/name = check disk
$ ls /etc/cron.d/check_disk.ncm-cron.cron
/etc/cron.d/check_disk.ncm-cron.cron
$ cat  /etc/cron.d/check_disk.ncm-cron.cron
... >> /var/log/check_disk.ncm-cron.log 2>&1
```
