### ISSUE TITLE
circular nlist causes uncaught error

### ISSUE THREAD

**Issue by quattor-releaser** [quattor/release#124]
The following template will create a circular nlist.  When the protect() method treats this structure, it then recurses indefinitely until it causes a StackOverflowException.  This exception is not caught and no error message is given to the user. 

object template test;

function f = {
SELF['A'] = nlist('a', 'BAD');
SELF;
};

'/result' = {
SELF['A'] = f();
SELF;
};

Reported by: loomisc

**Comment by linuxlovelz** [comment]
thanks
