### ISSUE TITLE
iptable.pm change required for NAT returns

### ISSUE THREAD

**Issue by quattor-releaser** [quattor/release#144]
Please change iptables.pm to include:

@{$iptables_totality{nat}{targets}}  = ('dnat', 'snat', 'return', 'masquerade', 'redirect');

rather than just:

@{$iptables_totality{nat}{targets}}  = ('dnat', 'snat', 'masquerade', 'redirect');

since the return rules must be added. 

Also, we have noted that this list is ordered, so adding the return after masquerade results in wrongly applied rules.

Reported by: eamonnkenny

**Comment by ned21** [comment]
Looks like this issue is no longer relevant since the iptables rewrite.
