### ISSUE TITLE
Patch for NCM cups component

### ISSUE THREAD

**Issue by quattor-releaser** [quattor/release#197]
Dears,

When using the ncm-cups component to a quattor template, if we define `"/software/components/cups/nodetype" = "client"`
then ncm-cups component does not stop running cups daemon. It should be the case, isn't it ?
Here's a fix:

``` diff
419a420,423
>         else {
>             # Be sure that the server is stopped if it is not enabled
>             $self->serviceControl($services{server},"stop")
>         }
```

the patch is based on:
http://quattor.svn.sourceforge.net/viewvc/quattor/trunk/ncm-components/core/ncm-cups/cups.pm.cin?revision=540

Reported by: Pansanel

**Comment by jrha** [comment]
This issue was moved to quattor/configuration-modules-core#1189
