### ISSUE TITLE
network

### ISSUE THREAD

**Issue by quattor-releaser** [quattor/release#199]
To configure JumboFrame we need to add a line concerning the MTU in the network interface file, here an example:
```
[root@wn025 ~]# more /etc/sysconfig/network-scripts/ifcfg-eth0
ONBOOT=yes
DEVICE=eth0
TYPE=Ethernet
BOOTPROTO=static
IPADDR=x.x.208.39
NETMASK=x.255.255.0
BROADCAST=x.x.208.255
MTU=9000
```

could you add this MTU option in the component ?
Thanks in advance
Christine Leroy

Reported by: clleroy

**Comment by jrha** [comment]
This appears to have been in the component since the beginning of our history.
