### ISSUE TITLE
deploy Nexus (or another package repository) for Quattor

### ISSUE THREAD

**Issue by quattor-releaser** [quattor/release#231]
Deploy a Nexus server \(or similar maven-compatible package repository\) for Quattor.  Ensure that built packages can be added to the repository.  Determine if this is the best model for saving the Quattor packages.

Reported by: loomisc

**Comment by jrha** [comment]
We now use the [Sonatype Nexus](https://oss.sonatype.org/content/repositories/snapshots/org/quattor/maven/) for build-tools and [our yum repositories](http://yum.quattor.org/) for packages, this seems to be working well for us for the time being.
