### ISSUE TITLE
Release aquilon-tools

### ISSUE THREAD

**Issue by stdweird** [quattor/release#267]
As soon as https://github.com/quattor/aquilon-tools/issues/12 is fixed

**Comment by jrha** [comment]
They'll only work easily on EL7 due to dependencies, so I won't be adding them to the main release.
Happy to release them separately at the same time though.

**Comment by jrha** [comment]
I would like to hack on this at the next workshop.

**Comment by jouvin** [comment]
From March 17 workshop: EL7 no longer an issue... it is a requirement for the broker too.

**Comment by jrha** [comment]
Available as http://yum.quattor.org/aquilon/aquilon-tools-1.46-1.x86_64.rpm, requires http://yum.quattor.org/externals/noarch/el7/python-termcolor-1.1.0-1.noarch.rpm.

**Comment by jrha** [comment]
@stdweird I leave it to your decision as to whether this meets the goal of "releasing" these

**Comment by stdweird** [comment]
Can you document what you did exactly, preferably in copy/paste code? :wink:
