### ISSUE TITLE
Broken dependencies for ncm-ceph, ncm-freeipa and ncm-opennebula

### ISSUE THREAD

**Issue by jnovy** [quattor/release#286]
Hi,

found this while testing repository dependencies satifability via repoclosure:

package: ncm-ceph-17.2.0-1.noarch from rhel7quattor
  unresolved deps: 
     perl(Git::Repository)
package: ncm-freeipa-17.2.0-1.noarch from rhel7quattor
  unresolved deps: 
     perl(Net::FreeIPA) >= 0:3.0.2
package: ncm-opennebula-17.2.0-1.noarch from rhel7quattor
  unresolved deps: 
     perl(Net::OpenNebula) >= 0:0.310.0

Seems these perl deps are not provided by neither EPEL nor mainline RHEL repositories. Are these custom perl modules which need to be part of Quttor repo then?

Thanks,
Jindrich

**Comment by jouvin** [comment]
`perl-Git-Repository` is in [quattor_externals](http://yum.quattor.org/externals), a required repo Quattor (in fact you need both the `noarch` and the `x86_64` repos for your OS version). I don't now about the others...

**Comment by alvarosimon** [comment]
Mmm.. in fact `Net::OpenNebula`   0.310.0 and `Net::FreeIPA`  3.0.2 are not available from quattor external repo http://yum.quattor.org/externals/noarch/el7/,  @stdweird @jrha could you include the missing packages?

**Comment by stdweird** [comment]
@jnovy @alvarosimon yes, that's my fault. i'll build rpms from cpan and have @jrha add them to the externals repo. (@jrha is there any chance to get access to the external repo to upload new versions?)

**Comment by jouvin** [comment]
I think I can do it...

**Comment by jrha** [comment]
@stdweird the repo server is run by LAL, so it is not up to me to give you access.

**Comment by stdweird** [comment]
@jnovy added dependencies
