### ISSUE TITLE
documentation-builder: add anotations from the template library

### ISSUE THREAD

**Issue by jouvin** [quattor/release#291]
To help completing the migration of the template library doc from Trac wiki (https://github.com/quattor/quattor.github.com/issues/214), it would be good to produce a documentation on ReadTheDocs based on annotations in the template library templates and probably a few static pages giving an overview of each template library subsets. 

We need to discuss how to group the annotations in the documentation produced... as this is more complex than for configuration modules. We could start by the list of each variables defined in each subset, even if this is not perfect but we may want to group them by feature or SCDB personality for example.

@wdpypere any thoughts? Any possible timeline?

**Comment by wdpypere** [comment]
@jouvin I had a look at it and would be possible. I am now working on RST instead of markdown in https://github.com/quattor/release/pull/327. If that is merged I can make the changes for adding the template library. If I don't forget, I should have time in January.
