### ISSUE TITLE
Add template-library-stratuslab to releases

### ISSUE THREAD

**Issue by jouvin** [quattor/release#61]
It would be good to have StratusLab-related template library and configuration modules part of the release. This requires a bit of restructuring of the current template-library-stratuslab repo (https://github.com/quattor/template-library-stratuslab/issues/6).

It would be good to have also this repo configured with the same milestones as others, part of the release dashboard...

**Comment by jrha** [comment]
Both template-library-stratuslab and template-library-openstack are tracked by the release backlog dashboard.

**Comment by ned21** [comment]
Superseded by #309 ?
