### ISSUE TITLE
Finalise externals repository on yum.quattor.org

### ISSUE THREAD

**Issue by jouvin** [quattor/release#62]
An `externals` repository was started a while ago on `yum.quattor.org`, creating confusion with the `externals` repository hosted on `quattorsrv.lal.in2p3.fr` and configured by default by the template libraries (with a few deprecated RPMs still required by some configuration modules). We need to merge both on `yum.quattor.org` and probably to have different `externals` repository for each OS major version as it tends to contain mostly OS-version dependent packages.

**Comment by jouvin** [comment]
I just fixed a couple of issues with new Quattor externals repositories :

- x86_64/el5 and x86_64/el7: repositories initialized despite they are empty so that you can start mirroring them.
- noarch/el6: repodata removed and regenerated to fix a problem wit perl-AppConfig-caf listed in the metadata but not present in the repo. Due to this, you may need to clean metadata before being able to synchronize with the repo.

**Comment by jrha** [comment]
So are we there yet? What else needs to be done?

**Comment by jouvin** [comment]
I'd say nothing! I use the new externals in production (with https://github.com/quattor/template-library-standard/issues/48) and I have not seen any problem. I'd suggest closing this issue.
