### ISSUE TITLE
build_all_repos: environment

### ISSUE THREAD

**Issue by jrha** [quattor/release#76]
`build_all_repos.sh` leaves a handy `env.sh` behind which sets up your environment for development.

However it currently only exports `PERL5LIB`.
In order to run all the unit tests `QUATTOR_TEST_TEMPLATE_LIBRARY_CORE` is also required.

I propose that this should be set to something like `$REPOSITORY/template-library-core/`.

**Comment by stdweird** [comment]
It's the default location for template-library-core (but might make sense to force it)

**Comment by stdweird** [comment]
@jrha what failed btw? (i'm a bit surprised it requires it) 
or is it for the release process? i guess so.

**Comment by jrha** [comment]
@stdweird exactly, it's for the release process!
