### ISSUE TITLE
metaconfig templates in template library bundle from 15.4 rc3 are out of date

### ISSUE THREAD

**Issue by stdweird** [quattor/release#95]

**Comment by stdweird** [comment]
#93

**Comment by jouvin** [comment]
From what I understood they should have been updated during the build process of the release. This probably means that we need to add something to the release script, isn't it?

**Comment by jrha** [comment]
It should be handled correctly by the release process already, but rc3 was a bit rushed to test the SL5 compatibility, I'll do another RC before final to shake this out.

**Comment by jrha** [comment]
Will test as part of RC4 (#96).

**Comment by jrha** [comment]
Hmm, it does seem to be broken.

**Comment by jrha** [comment]
Ok, so the release script is doing the right-thing™, but fails because the pan templates do not appear in the target directory to be copied across, odd because they do exist in the target directory created by `build_all_repos.sh`

**Comment by stdweird** [comment]
because https://github.com/quattor/release/blob/master/src/releasing/releaser.sh#L53 doesn't produce the pan templates, currently only `mvn test` does.
there's an issue somewhere to track this tough

**Comment by jrha** [comment]
I just came to the same conclusion. I wonder why it seemed to work before...

**Comment by jrha** [comment]
Seems to be fixed by #97, although some templates (eg. graylog2 were not updated).
